### ISSUE TITLE
Stick the sheet at bottom

### ISSUE THREAD

**Issue by hemangshah** [gametimesf/GTSheet#13]
Is there a way where we can swipe up the sheet from bottom to top as requires and when swipe it down that it will not hide completely but visible by half height of the actual height? And user can do interaction in both the parent as well as the sheet view controllers?

**Comment by mattbanach** [comment]
Sounds like what you are describing is very similar to the iOS Maps app. The goal of this library wasn't to support that functionality, but be closer to the Material Design Bottom Sheet pattern. Thus, we won't be supporting this behavior.
