### ISSUE TITLE
"broken" on iphone X

### ISSUE THREAD

**Issue by gerchicov-bp** [gametimesf/GTSheet#4]
Look at your screenshot from readme file. According to apple guidelines you shouldn't overlap the bottom horizontal line with active UI elements.

Note I could understood if your project just didn't support iphone X. But placing this incorrect picture in readme may confuse programmers and they may get a reject from apple on app submission

**Comment by mattbanach** [comment]
Thanks for your comment! You are correct that Apple recommends against placing controls under the home indicator. In the case of a `UIScrollView`, it is expected that content flow under the home indicator and that the end of the `UIScrollView` includes insets that account for the safe area. Please see examples of first party iOS apps, like Music or Mail, where this is the case.
