### ISSUE TITLE
Expand

### ISSUE THREAD

**Issue by CavalcanteLeo** [gametimesf/GTSheet#5]
Is that possible to scroll/swipe up a tableview/collectionview/scrollview to expand?
Open up half screen, but a possible way to expand it to fullscreen 

Or set the distance from top to the modal

**Comment by mattbanach** [comment]
Unfortunately, the library doesn't currently support the interaction you are describing-- Am I right in assuming you are looking to do something like the native Android bottom sheet does? In any case, while you can dynamically resize a sheet (check out the sample project for how that is done), the library doesn't support an interaction using a gesture out of the box.
